### ISSUE TITLE
SQL Login Failure - External DB with Workgroup BnR Server

### ISSUE THREAD

**Issue by HCN3atCDW** [VeeamHub/veeam-healthcheck#10]
**Describe the bug**
Attempting to run script on a non-domain joined BnR server (V11a) with an external SQL server using integrated authentication fails with Login failures to the SQL DB due to untrusted domain. As per security best practices the BnR server also had the BnR Console uninstalled.

**To Reproduce**
1. Run Script as elevated user
2. Accept Terms
3. Click Run
4. Green Working block runs for about 5-10 seconds and stops
5. VLC folder is created but no output is present
6. Log file (screenshot attached) shows SQL login error

**Expected behavior**
Script should at minimum prompt for SQL DB credentials if unable to use default Veeam BnR credentials. 
<img width="485" alt="VHC Log" src="https://user-images.githubusercontent.com/66739741/186934956-c99e8dc4-9d68-468d-aa05-fcbacabcaaee.png">

**Comment by adamcongdon** [comment]
Hi, Thanks for the feedback.

The SQL Commands should be auxiliary and not cause failure. I will fix that.

As for prompting for SQL creds. Most feedback received so far was more automation and less interaction. So a pop-up window would not be ideal.

I'm thinking of maybe adding CLI switch to offer ability to specify creds. Or maybe pre-populate the creds and allow option to change them before execution. What are you thoughts on that?

**Comment by HCN3atCDW** [comment]
I would be fine with a CLI switch if needed. The main concern I have which I didn’t investigate in the code is the credentials. We have a non-domain joined BnR server with a local administrator credential using an external, domain-joined SQL server as the database server. The script “ran” but created a bunch of 0 byte CSVs and the log file had the errors I shared with you. I am not sure how the script is authenticating to the database. We were logged into the BnR server with the local administrator user that is also a BnR administrator. As per best practices for security the Veeam Console was uninstalled from the BnR server so it only had the BnR services on it if that matters as well.

_____________________
Herb C. Numrich
Principal Consulting Engineer – Data Center Solutions | CDW
Phone: 920.996.3125 | Mobile: 920.475.5738 | Central Time Zone
UPCOMING OUT OF OFFICE DATES:  9/2, 9/23-30

http://www.cdw.com/it-solutions/data-center/virtualization.aspx

From: Adam Congdon ***@***.***>
Date: Friday, August 26, 2022 at 11:54 AM
To: VeeamHub/veeam-healthcheck ***@***.***>
Cc: Herb Numrich ***@***.***>, Author ***@***.***>
Subject: Re: [VeeamHub/veeam-healthcheck] SQL Login Failure - External DB with Workgroup BnR Server (Issue #10)
EXTERNAL EMAIL

Hi, Thanks for the feedback.

The SQL Commands should be auxiliary and not cause failure. I will fix that.

As for prompting for SQL creds. Most feedback received so far was more automation and less interaction. So a pop-up window would not be ideal.

I'm thinking of maybe adding CLI switch to offer ability to specify creds. Or maybe pre-populate the creds and allow option to change them before execution. What are you thoughts on that?

**Comment by adamcongdon** [comment]
Issue was that the vHC was being executed on a B&R server that had the B&R Console uninstalled. In this case, Remote execution would be required. However, that is not yet implemented. SQL errors are benign. Workaround was to run PS scripts (from \Tools folder) and then I used a debug mode to import & report.

Coming features:
- CLI /import feature
- - will help with scenario if the program breaks
- Remote Exec
- - Idea is to feed CLI the B&R Server Name(s) and run a vHC against the provided server.
