### ISSUE TITLE
Job Session Report columns incorrect

### ISSUE THREAD

**Issue by jsundin-Insight** [VeeamHub/veeam-healthcheck#15]
**Describe the bug**
In the Job Session Summary report, the column headers for Min Time and Avg Time look to be reversed.

**To Reproduce**
1. Go to Job Session Summary report.
2. Look at Min Time, Max Time and Avg Time.
3. You will see that in all cases, Avg time is *higher* than Min Time.

**Expected behavior**
The column titles or the underlying data in the two columns should be swapped.

**Screenshots**
<img width="440" alt="Screenshot 2023-05-05 at 11 33 08 AM" src="https://user-images.githubusercontent.com/109970485/236515483-c01de551-d402-4e78-8d08-e3368a79bc5b.png">

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by adamcongdon** [comment]
Hi,

In which version of the vHC do you experience this? In the latest release, this appears to have been corrected as far as my testing shows. Going through the history this was [resolved on March 6](https://github.com/VeeamHub/veeam-healthcheck/commit/ef2d591117c31ee39454e133035d5c36321d1293#diff-44348c75e2115a2cdd42fe372e029d6b47e67240142c7dac4ebe6b7e752a1b5a) and has been published since then.

**Comment by jsundin-Insight** [comment]
I’ll double check on a new one I ran for another customer this week and have not analyzed yet.

I probably got one rev behind.

Thank you for this great tool.  I use it with many customers as I perform data protection assessments.

Jeff

Sent from my iPhone
[signature_1877190530]

JEFF SUNDIN  | Senior Assessment Engineer | Insight
w. 424.220.6779  |  c. 503.708.9718 (Central Time Zone)
***@***.******@***.***> |  insight.com<http://www.insight.com/>



On May 19, 2023, at 10:08 AM, Adam Congdon ***@***.***> wrote:

﻿
External Message - Please be cautious when opening links or attachments in email


Hi,

In which version of the vHC do you experience this? In the latest release, this appears to have been corrected as far as my testing shows. Going through the history this was resolved on March 6<https://github.com/VeeamHub/veeam-healthcheck/commit/ef2d591117c31ee39454e133035d5c36321d1293#diff-44348c75e2115a2cdd42fe372e029d6b47e67240142c7dac4ebe6b7e752a1b5a> and has been published since then.

**Comment by jsundin-Insight** [comment]
Thank you, it looks correct now.

I appreciate the follow-up.

Jeff


[signature_349493159]

JEFF SUNDIN, Security+, PSCC-3  | Senior Assessment Engineer | Insight
w. 424.220.6779  |  c. 503.708.9718 (Central Time Zone)
***@***.******@***.***> |  insight.com<http://www.insight.com>
--

Upcoming Out of Office
May 18-19, 26
July 3-7
Sep 4-8
Oct 9


From: Adam Congdon ***@***.***>
Date: Friday, May 19, 2023 at 10:08 AM
To: VeeamHub/veeam-healthcheck ***@***.***>
Cc: Sundin, Jeff ***@***.***>, Author ***@***.***>
Subject: Re: [VeeamHub/veeam-healthcheck] Job Session Report columns incorrect (Issue #15)
External Message - Please be cautious when opening links or attachments in email


Hi,

In which version of the vHC do you experience this? In the latest release, this appears to have been corrected as far as my testing shows. Going through the history this was resolved on March 6<https://github.com/VeeamHub/veeam-healthcheck/commit/ef2d591117c31ee39454e133035d5c36321d1293#diff-44348c75e2115a2cdd42fe372e029d6b47e67240142c7dac4ebe6b7e752a1b5a> and has been published since then.
