### ISSUE TITLE
Job Session Summary Shows Incorrect Information

### ISSUE THREAD

**Issue by dgroeschen** [VeeamHub/veeam-healthcheck#17]
**Describe the bug**
using default options the Job Session Summary report displays the same information over and over for each job as opposed to individual job status information as expected

**To Reproduce**
1. Run VeeamHealthCheck.exe /run
2. Open html page scroll to Job Session Summary
3. Expand

**Expected behavior**
Job Session Summary should be showing the individual status of each policy vs a combined / 1st job policy summary

**Screenshots**
![image](https://github.com/VeeamHub/veeam-healthcheck/assets/7918855/ae729797-bcca-4c71-bd3d-ccee3e8ed344)

This is ran against 12.0.0.1420 P20230412 environment

**Comment by adamcongdon** [comment]
Hi, thanks for reporting. Checking it out.

**Comment by adamcongdon** [comment]
Issue is resolved in 1.0.3.689
