### ISSUE TITLE
Link in HTML report is wrong

### ISSUE THREAD

**Issue by StefanZ8n** [VeeamHub/veeam-healthcheck#4]
The link to the individual job session folder from the HTML report is wrong. 

**To Reproduce**
1. Run report with default settings
2. Click on the link in the HTML Report (`file:///C:/temp/vHC/JobSessionReports`)
3. See error

**Expected behavior**
Use correct link (`file:///C:/temp/vHC/Anonymous/JobSessionReports` in my case - or `Original` instead of `Anonymous` when not anonymized)

**Screenshots**
N/A

**Versions**
vHC v1.0.1.1272

**Comment by adamcongdon** [comment]
Issue resolved. Will be included in next update.
