### ISSUE TITLE
SQL Express max cores

### ISSUE THREAD

**Issue by StefanZ8n** [VeeamHub/veeam-healthcheck#5]
SQL Cores number seems strange. 
The system only has 4 cores and the SQL express limit is 4 logical cores (on the first socket). Don't know where the 16 comes from, but that could be optimized.

**To Reproduce**
1.Run vHC on default VBR11 installation with SQL Express, 4 cores on the VM
2. See HTML Report

**Expected behavior**
Show 4 - basically out of the 4 logical cores for SQL Express (as we know the edition) or at least because there are no 16 cores available on the VM.

**Screenshots**
![image](https://user-images.githubusercontent.com/5945920/172831853-8dad3a4f-d49a-4afd-8410-afb997959157.png)

vHC: v1.0.1.1272

**Comment by adamcongdon** [comment]
Issue is fixed. Bug was in logic trying to account for multi-threading. This will be included in the next release.
