### ISSUE TITLE
Ability to execute Veeam Health Check through command line/programatically

### ISSUE THREAD

**Issue by tonyvalverde** [VeeamHub/veeam-healthcheck#6]
The Veeam Health check tool requires interactive operation to execute which greatly limits how we can use it as it requires user manual intervention every time it is executed.  This results in it no being executed, or rarely especially for large environments with multiple VBR servers.

We would like to schedule the execution of the Veeam Health Check so it can be run weekly and can be run programmatically remotely.   This would require updating it so it can be ran through command line and/or programmatically.  

Command line execution can be achieved with simple invocation of the input parameters in command line itself (preferred) or in an input file which we can schedule it locally and remotely execute through scripting automation whereby we can publish the results either through email or on a health website page.

Simply allowing command line execution will allow a scripting automation to be used significantly expanding the Veeam Health Check capabilities.

**Comment by adamcongdon** [comment]
Hi Tony,

Thanks for the feedback. I'm testing out CLI execution. As a starter, I have the ability to run the tool from CLI to default location, or to specify custom output location. Using CLI, I assume showing Explorer or HTML report are not helpful and as such I have left out those switches.

`C:\temp> .\VeeamHealthCheck.exe help
HELP MENU:
run     Executes the program via CLI
outdir: Specifies desired location for HTML reports. Usage: "outdir:D:\example". Default = C:\temp\vHC

EXAMPLES:
1. Run to default location:      .\VeeamHealthCheck.exe run
2. Run to custom location:       .\VeeamHealthCheck.exe run outdir:\\myshare\folder`

Does that seem sufficient for what you're trying to accomplish or would you like to see something different?

-Adam
