### ISSUE TITLE
Registry Keys: Object Arrays Not Handled Correctly in Output

### ISSUE THREAD

**Issue by cslSWds07** [VeeamHub/veeam-healthcheck#7]
**Describe the bug**
The "Non-Default Registry Keys" section outputs "System.String[]" if more than one value is returned for the Registry Key.

**To Reproduce**
1. Add a multiple value registry key (Ex. NFSLinuxMountOptions with multiple NFS mounts)
2. Run Health Check
3. Scroll down to 'Non-Default Registry Keys'
5. See error

**Expected behavior**
The expected behavior would be to see each entry listed and either be comma separated or line separated. My personal preference would be for line separation.

**Screenshots**
![image](https://user-images.githubusercontent.com/99510104/180086472-6299c519-61e7-4cfd-b86f-936cd418d649.png)

**Desktop (please complete the following information):**
N/A

**Additional context**
This is a default behavior when exporting object arrays to CSV in PowerShell. Simply adding a " -join ','" (or similar ) should resolve this issue.

I haven't checked multiple versions of the Health Check tool but this is known to be present in 1.0.1.1273.

**Comment by adamcongdon** [comment]
Hi, thank you for the feedback.

I'll look into this. Sorry for delay!

**Comment by adamcongdon** [comment]
Fixing this by migrating registry queries to C# and away from PowerShell. Will be published in the next release.
