### ISSUE TITLE
Include GFS policy in the BJ e BCJ

### ISSUE THREAD

**Issue by eduzimrs** [VeeamHub/veeam-healthcheck#9]
**Is your feature request related to a problem? Please describe.**
Not a problem, but to add an new feature 

**Describe the solution you'd like**
Add the GFS policy for Backup and Backup Copy Jobs, that would be very good.

**Describe alternatives you've considered**
I can get it only running PS custom scripts, but adding to to this one would improve its value.

**Comment by adamcongdon** [comment]
Hi, thanks for the feedback!

I do have plans to add this. I will mark when the feature makes it.

**Comment by adamcongdon** [comment]
GFS policies added to jobs now in v2.0
